Repository codethesaurus/codethesaur.us, pull requests merged in 2020-10, with the labels that each got.

#29 Add Reference template, fix Heroku issues
  Procfile
  codethesaurus/settings.py
  web/templates/index.html
  web/templates/reference.html
Labels: bug, ci/cd

#32 Corrects readme to use requirements.txt for dependencies
  README.md
Labels: documentation, hacktoberfest

#37 Revise Code of Conduct file with correct contact and questions section
  CODE_OF_CONDUCT.md
Labels: documentation

#43 Fix #42 keyerror on /compare and make view more robust
  .gitignore
  manage.py
  web/templates/compare.html
  web/views.py
Labels: hacktoberfest-accepted

#45 Issue #44: Unsupported items shouldn't be formatted as code.
  web/templates/compare.html
  web/templates/comparecard.html
  web/templates/reference.html
  web/templatetags/__init__.py
  web/templatetags/templatetags.py
Labels: hacktoberfest-accepted

#71 Revise CONTRIBUTING.md file to reflect latest changes to the project
  CODE_OF_CONDUCT_REPORTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#63 update using for mac
  README.md
Labels: hacktoberfest-accepted

#72 Update README with Windows directions
  README.md
Labels: hacktoberfest-accepted

#52 Added simple feature request and bug report templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: hacktoberfest-accepted

#62 Adds random programming language entries to home page dropdowns
  web/templates/index.html
  web/views.py
Labels: hacktoberfest-accepted

#77 Add link to contributors to footer
  web/static/js/contributors.js
  web/templates/base.html
Labels: hacktoberfest-accepted

#79 Issue 73
  web/views.py
Labels: hacktoberfest-accepted

#80 Issue 21 homepage design
  web/static/css/app.css
  web/templates/about.html
  web/templates/base.html
  web/templates/index.html
Labels: hacktoberfest-accepted

#83 Unit tests for django
  web/tests.py
  web/tests/__init__.py
  web/tests/test_controllers.py
  web/tests/test_models.py
  web/tests/test_urls.py
  web/tests/test_views.py
Labels: hacktoberfest-accepted
